apiVersion: argoproj.io/v1alpha1
kind: ClusterAnalysisTemplate
metadata:
  name: pingpong-cpu-check
spec:
  args:
  - name: namespace
  - name: threshold
    value: "1.0"
  metrics:
  - name: namespace-cpu
    interval: 1m
    count: 5
    successCondition: result <= {{args.threshold}}
    failureCondition: result > {{args.threshold}}
    provider:
      prometheus:
        address: http://prometheus.monitoring.svc:9090
        query: |
          sum(rate(container_cpu_usage_seconds_total{namespace="{{args.namespace}}"}[5m]))
