# Use official Node.js LTS image
FROM node:20-alpine

# Create app directory
WORKDIR /usr/src/app

# Install dependencies
COPY package-reader.json ./package.json
RUN npm install

# Copy app source
COPY index-reader.js ./

# Start the app
CMD ["npm", "start"]
