apiVersion: v1
kind: Service
metadata:
  name: ping-pong
  namespace: exercises
spec:
  selector:
    app: ping-pong
    variant: local
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
