apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
        - name: todo-backend
          image: captainlevi20/todo-backend:1.0
          envFrom:
            - configMapRef:
                name: todo-backend-config
          ports:
            - containerPort: 3000

---
---
apiVersion: v1
kind: Service
metadata:
  name: todo-backend-service
  namespace: project
spec:
  selector:
    app: todo-backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
