apiVersion: batch/v1
kind: CronJob
metadata:
  name: create-random-todo
spec:
  schedule: "0 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: create-random-todo
              image: curlimages/curl:8.2.1
              imagePullPolicy: IfNotPresent
              command:
                - /bin/sh
                - -c
                - |
                  set -eu
                  location=$(curl -s -D - -o /dev/null --max-redirs 0 https://en.wikipedia.org/wiki/Special:Random \
                    | awk '/^[Ll]ocation:/{print $2}' | tr -d '\r')
                  if [ -z "$location" ]; then
                    echo "No se obtuvo Location; abortando"
                    exit 0
                  fi
                  text="Read $location"
                  json=$(printf '%s' "{\"text\":\"%s\"}" "$text")
                  curl -s -X POST -H 'Content-Type: application/json' -d "$json" http://todo-backend-service:3000/todos || true
